Repository viralvaghela/hacktoberfest_2021, pull requests merged in 2021-10, with the labels that each got.

#1 Calculator.java
  java/Calculator.java
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#2 Codechef Chef and String Problem solution
  cpp/Codechef_Chef and String_XYSTR.cpp
Labels: hacktoberfest-accepted, appreciation

#3 Added new java program to implement linear search
  java/LinearSearchExample.java
Labels: hacktoberfest-accepted, appreciation

#4 CodeChef Count subarrays problem solution added
  cpp/CodeChef_Count_Subarrays.cpp
Labels: hacktoberfest-accepted, appreciation

#5 Binary search tree
  c/binary_search_tree.c
Labels: hacktoberfest-accepted, appreciation

#6 Create SearchSubString.py
  python/SearchSubString.py
Labels: hacktoberfest-accepted, appreciation

#7 Square root using BS
  cpp/SquareRootOfInteger.cpp
Labels: hacktoberfest-accepted, appreciation

#9 Added implementation of Hashing using arrays
  java/Hashing_using_array.java
Labels: hacktoberfest-accepted, appreciation

#10 Added Merge sort Generic Class in java
  .DS_Store
  java/MyMergeSort.java
Labels: hacktoberfest-accepted, appreciation

#11 added binary search tree implementation
  binarySearchTree.cpp
Labels: hacktoberfest-accepted, appreciation

#12 Counting max number of character in a string
  python/maxOccuring.py
Labels: hacktoberfest-accepted, appreciation

#13 findnodeinLinkedList.cpp added
  cpp/findnodeinLinkedList.cpp
Labels: hacktoberfest-accepted, appreciation

#16 Create Linear_search.c
  c/Linear_search.c
Labels: hacktoberfest-accepted, appreciation

#21 Feistel Cipher Algorithm using python
  python/FeistelCipher.py
Labels: hacktoberfest-accepted, appreciation

#23 Create Bubblesort.py
  python/Bubblesort.py
Labels: hacktoberfest-accepted, appreciation

#14 adding Finding Factorial From User Input script
  python/FindingFactorialFromInput.py
Labels: hacktoberfest-accepted, appreciation

#18 Leaky Bucket Algorithm in Python
  python/LeakyBucket.py
Labels: hacktoberfest-accepted, appreciation

#22 Create Bubblesort.cpp
  cpp/Bubblesort.cpp
Labels: hacktoberfest-accepted, appreciation

#19 Create FindDuplicates.java
  java/FindDuplicates.java
Labels: hacktoberfest-accepted, appreciation

#20 Added String Powerset in CPP
  cpp/String_powerset.cpp
Labels: hacktoberfest-accepted, appreciation

#30 Add HTML Example
  html/ButtonGradiant.html
  html/Headding.html
Labels: hacktoberfest-accepted, appreciation

#34 Correct the mistakes of md files of some folders and Text to Image in Python
  php/readme.md
  python/TextToImage.py
  python/readme.md
  ruby/readme.md
  swift/readme.md
Labels: hacktoberfest-accepted, appreciation

#45 Created OrderAgnosticBinarySearch program
  java/OrderAgnosticBinarySearch.java
Labels: hacktoberfest-accepted, appreciation

#24 User defined map function
  python/myMap.py
Labels: hacktoberfest-accepted, appreciation

#25 Create MergeSort.py
  cpp/GCD.cpp
  cpp/MergeSort.cpp
  python/MergeSort.py
Labels: hacktoberfest-accepted, appreciation

#31 Added Array Implementation of Stack
  java/Stack.java
Labels: hacktoberfest-accepted, appreciation

#26 Added Program for Singly Linked List Operations using CPP
  cpp/Singly_Linked_List_Operations.cpp
Labels: hacktoberfest-accepted, appreciation

#33 4 Famous C++ Program Added
  cpp/DnCMaximumMinimum.cpp
  cpp/MatrixChainMultiplication.cpp
  cpp/dncMatrixMultiplication.cpp
  cpp/strassens.cpp
Labels: hacktoberfest-accepted, appreciation

#35 Rename binarySearchTree.cpp to cpp/binarySearchTree.cpp
  cpp/binarySearchTree.cpp
Labels: hacktoberfest-accepted, appreciation

#57 Add a JS Maze Generator/Solver
  js/maze-solver/README.md
  js/maze-solver/index.html
  js/maze-solver/script.js
  js/maze-solver/style.css
Labels: hacktoberfest-accepted, appreciation

#42 Add Calendar.py file
  python/calendar.py
Labels: hacktoberfest-accepted, appreciation

#52 ValidSudoku
  java/ValidSudoku.java
Labels: hacktoberfest-accepted, appreciation

#37 add Bipartite graph check
  cpp/Bipartite_Graph.cpp
Labels: hacktoberfest-accepted, appreciation

#27 Implementing postfix Evaluation in C
  c/postfixEvaluation.c
Labels: hacktoberfest-accepted, appreciation

#56 Add React Random Quote Generator
  js/quote-generator/README.md
  js/quote-generator/index.html
  js/quote-generator/script.js
  js/quote-generator/style.css
Labels: hacktoberfest-accepted, appreciation

#60 Create hangman game.cpp
  cpp/hangman game.cpp
Labels: hacktoberfest-accepted, appreciation

#54 Create Themes.dart
  dart/Themes.dart
Labels: hacktoberfest-accepted, appreciation

#44 error resolved in java programs and added a new file
  java/FindDuplicates.java
  java/Hashing_using_array.java
  python/pyPasswordGenerator.py
  python/readme.md
Labels: hacktoberfest-accepted, appreciation

#63 Min Swaps to sort array
  cpp/minimum_swaps_to_sort.cpp
Labels: hacktoberfest-accepted, appreciation

#69 Quick-Sort in C++
  cpp/quick_sort.cpp
Labels: hacktoberfest-accepted, appreciation

#82 Added matrix-addition C Program
  c/matrix-addition.c
Labels: hacktoberfest-accepted, appreciation

#83 Create youtubedownloader.py
  python/youtubedownloader.py
Labels: hacktoberfest-accepted, appreciation

#81 Create urlshortner.py
  python/urlshortner.py
Labels: hacktoberfest-accepted, appreciation

#84 added js weather app
  js/weather-app/index.html
  js/weather-app/readme.md
  js/weather-app/script.js
  js/weather-app/style.css
Labels: hacktoberfest-accepted, appreciation

#85 Added Notes app in dart
  dart/notes_flutter/.gitignore
  dart/notes_flutter/.metadata
  dart/notes_flutter/README.md
  dart/notes_flutter/android/.gitignore
  dart/notes_flutter/android/app/build.gradle
  dart/notes_flutter/android/app/src/debug/AndroidManifest.xml
  dart/notes_flutter/android/app/src/main/AndroidManifest.xml
  dart/notes_flutter/android/app/src/main/kotlin/com/example/notes_flutter/MainActivity.kt
  dart/notes_flutter/android/app/src/main/res/drawable-v21/launch_background.xml
  dart/notes_flutter/android/app/src/main/res/drawable/launch_background.xml
  dart/notes_flutter/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  dart/notes_flutter/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  dart/notes_flutter/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  dart/notes_flutter/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  dart/notes_flutter/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  dart/notes_flutter/android/app/src/main/res/values-night/styles.xml
  dart/notes_flutter/android/app/src/main/res/values/styles.xml
  dart/notes_flutter/android/app/src/profile/AndroidManifest.xml
  dart/notes_flutter/android/build.gradle
  dart/notes_flutter/android/gradle.properties
  dart/notes_flutter/android/gradle/wrapper/gradle-wrapper.properties
  dart/notes_flutter/android/settings.gradle
  dart/notes_flutter/asset/note.png
  dart/notes_flutter/lib/LocalDatabase/LocalDatabase.dart
  dart/notes_flutter/lib/Screens/EditNote.dart
  dart/notes_flutter/lib/Screens/HomeScreen.dart
  dart/notes_flutter/lib/Screens/SplashScreen.dart
  dart/notes_flutter/lib/UI/CustomSideDrawer.dart
  dart/notes_flutter/lib/UI/DeleteAlertDailog.dart
  dart/notes_flutter/lib/UI/NoteForm.dart
  dart/notes_flutter/lib/UI/card.dart
  dart/notes_flutter/lib/bloc/Bloc.dart
  dart/notes_flutter/lib/bloc/BlocListner.dart
  dart/notes_flutter/lib/bloc/BlocProvider.dart
  dart/notes_flutter/lib/bloc/NoteActionsBloc/NoteActionBloc.dart
  dart/notes_flutter/lib/bloc/NoteActionsBloc/NoteActionEvent.dart
  dart/notes_flutter/lib/bloc/NoteActionsBloc/NoteActionState.dart
  dart/notes_flutter/lib/bloc/NoteListBloc/NoteListBloc.dart
  dart/notes_flutter/lib/bloc/NoteListBloc/NoteListEvent.dart
  dart/notes_flutter/lib/bloc/NoteListBloc/NoteListState.dart
  dart/notes_flutter/lib/bloc/ThemeBloc/ThemeBloc.dart
  dart/notes_flutter/lib/bloc/ThemeBloc/ThemeEvent.dart
  dart/notes_flutter/lib/bloc/ThemeBloc/ThemeState.dart
  dart/notes_flutter/lib/constants/Constants.dart
  dart/notes_flutter/lib/main.dart
  dart/notes_flutter/lib/model/Notes.dart
  dart/notes_flutter/pubspec.lock
  dart/notes_flutter/pubspec.yaml
  dart/notes_flutter/screenshots/ss1.jpg
  dart/notes_flutter/screenshots/ss2.jpg
  dart/notes_flutter/screenshots/ss3.jpg
  dart/notes_flutter/screenshots/ss4.jpg
  dart/notes_flutter/screenshots/ss5.jpg
  dart/notes_flutter/screenshots/ss6.jpg
  dart/notes_flutter/test/widget_test.dart
  dart/notes_flutter/web/favicon.png
  dart/notes_flutter/web/icons/Icon-192.png
  dart/notes_flutter/web/icons/Icon-512.png
  dart/notes_flutter/web/index.html
  dart/notes_flutter/web/manifest.json
Labels: hacktoberfest-accepted, appreciation

#92 Added The Database operations code in php - HacktoberFest 2021
  php/All_DataBase_Operations_Code.php
  php/To-Do-List/Login.php
  php/To-Do-List/README.md
  php/To-Do-List/Signup.php
  php/To-Do-List/Site.png
  php/To-Do-List/Site_Icon/After_Signup.html
  php/To-Do-List/Site_Icon/Login.html
  php/To-Do-List/Site_Icon/SignUp.html
  php/To-Do-List/Site_Icon/about.txt
  php/To-Do-List/Site_Icon/android-chrome-192x192.png
  php/To-Do-List/Site_Icon/android-chrome-512x512.png
  php/To-Do-List/Site_Icon/apple-touch-icon.png
  php/To-Do-List/Site_Icon/favicon-16x16.png
  php/To-Do-List/Site_Icon/favicon-32x32.png
  php/To-Do-List/Site_Icon/favicon.ico
  php/To-Do-List/Site_Icon/site.webmanifest
  php/To-Do-List/User_data.php
  php/To-Do-List/login.jpg
  php/To-Do-List/signup.jpg
  php/To-Do-List/style.css
Labels: hacktoberfest-accepted, appreciation

#93 A python3 Code to change the MAC address of linux distributions.
  python/linux_mac_changer.py
Labels: hacktoberfest-accepted, appreciation

#78 merge html google home page project
  html/google_home_saugat-rimal.html
Labels: hacktoberfest-accepted, appreciation

#28 Added Kadane's Algo and Queue using 2 Stacks
  cpp/Kadane_Algo.cpp
  cpp/Queue_Using_Stacks.cpp
Labels: hacktoberfest-accepted, appreciation

#38 Create GRAM_SCHMIDT_PROCESS.java
  java/GRAM_SCHMIDT_PROCESS.java
Labels: hacktoberfest-accepted

#40 Mid point of linked list code added
  cpp/midpointofLL.cpp
Labels: hacktoberfest-accepted, appreciation

#41 Create Breaking_the_record.js
  js/Breaking_the_record.js
Labels: hacktoberfest-accepted, appreciation

#43 Add algorithm for balanced paranthesis in python
  python/balanced_paranthesis.py
Labels: hacktoberfest-accepted, appreciation

#46 I add CPP files
  cpp/Pallindromenumber.cpp
  cpp/decimal_to_binary.cpp
  cpp/primenumber.cpp
Labels: hacktoberfest-accepted

#47 Added a Missing Number program, a famous interview problem!!
  java/MissingNumber.java
Labels: hacktoberfest-accepted, appreciation

#48 Added python program
  python/PalindromeStringChecker.py
Labels: hacktoberfest-accepted

#49 Created Star Using Turtle
  python/Star_using_Turtle.py
Labels: hacktoberfest-accepted, appreciation

#109 feat : js/tic-tac-toe game created
  js/tic-tac-toe/index.html
  js/tic-tac-toe/script.js
  js/tic-tac-toe/style.css
Labels: hacktoberfest-accepted, appreciation

#55 Strassens algorithm for matrix multiplication
  cpp/strassens algorithm.cpp
Labels: good first issue, hacktoberfest-accepted, appreciation

#58 add java prog to check prime number
  .gitignore
  java/Prime.java
Labels: hacktoberfest-accepted, appreciation

#64 Added Some C# Practice scripts.
  C#/C#.csproj
  C#/MinMaxArray.cs
  C#/NegativeASide.cs
  C#/ReverseArray.cs
  C#/RotateArr.cs
  C#/bin/Debug/netcoreapp3.1/C#.deps.json
  C#/bin/Debug/netcoreapp3.1/C#.dll
  C#/bin/Debug/netcoreapp3.1/C#.exe
  C#/bin/Debug/netcoreapp3.1/C#.pdb
  C#/bin/Debug/netcoreapp3.1/C#.runtimeconfig.dev.json
  C#/bin/Debug/netcoreapp3.1/C#.runtimeconfig.json
  C#/kthMaxArray.cs
  C#/obj/C#.csproj.nuget.dgspec.json
  C#/obj/C#.csproj.nuget.g.props
  C#/obj/C#.csproj.nuget.g.targets
  C#/obj/Debug/netcoreapp3.1/C#.AssemblyInfo.cs
  C#/obj/Debug/netcoreapp3.1/C#.AssemblyInfoInputs.cache
  C#/obj/Debug/netcoreapp3.1/C#.assets.cache
  C#/obj/Debug/netcoreapp3.1/C#.csproj.AssemblyReference.cache
  C#/obj/Debug/netcoreapp3.1/C#.csproj.CoreCompileInputs.cache
  C#/obj/Debug/netcoreapp3.1/C#.csproj.FileListAbsolute.txt
  C#/obj/Debug/netcoreapp3.1/C#.csprojAssemblyReference.cache
  C#/obj/Debug/netcoreapp3.1/C#.dll
  C#/obj/Debug/netcoreapp3.1/C#.exe
  C#/obj/Debug/netcoreapp3.1/C#.genruntimeconfig.cache
  C#/obj/Debug/netcoreapp3.1/C#.pdb
  C#/obj/project.assets.json
  C#/obj/project.nuget.cache
Labels: hacktoberfest-accepted, appreciation

#65 added famous problem: 4-Sum
  cpp/4Sum.cpp
Labels: hacktoberfest-accepted, appreciation

#118 Added BMI Finder Python code
  python/BmiCalculator.py
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#51 Created Pattern.c
  c/Pattern.c
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#67 topological sort code
  cpp/tsort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#70 Stack Implementation
  cpp/stack.cpp
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#71 Quicksort Java code
  java/quick_sort.java
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#72 Create Minimum Cost of ropes.cpp
  cpp/Minimum Cost of ropes.cpp
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#73 HeapSort
  cpp/HeapSort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#75 add code for finding max xor of 2 numbers using Trie
  cpp/maxXorOf2NumbersUsingTrie.cpp
Labels: good first issue, hacktoberfest-accepted, appreciation

#76 Add CPP code for 2D Parity Generator
  cpp/2D-ParityGenerator.cpp
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#77 Byte to hex string function added
  java/byte2hex.java
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#80 added a landing page website
  js/landing-page/book.png
  js/landing-page/icon.png
  js/landing-page/index.html
  js/landing-page/style.css
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#50 Created Registration form using Swings in java
  java/Registration_form.java
Labels: documentation, hacktoberfest, hacktoberfest-accepted, appreciation

#74 QuickSort Python Code
  python/QuickSort.py
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#126 Added C++ code for KMP String matching algorithm
  cpp/KMP_Substring_Search.cpp
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#87 Added Search in rotated sorted array.cpp
  cpp/Search in rotated sorted array.cpp
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#141 Create bubbleSort_optimized.c
  c/bubbleSort_optimized.c
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#89 Added code to Encrypt the String Given
  python/string_Encryptor.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, appreciation

#91 remove_repeated_letters cpp code added
  cpp/remove_repeated_letters.cpp
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#94 Create AnandSort.cpp
  cpp/AnandSort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#95 Added Floyd Warshall Algorithm
  cpp/Floyd_Warshall.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#86 Create splash_screen.dart
  dart/splash_screen.dart
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#88 Added Bucket Sort
  cpp/BucketSort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#96 Create TripletSum.cpp
  cpp/TripletSum.cpp
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#97 Create Height_0f_a_binary_tree.cpp
  cpp/Height_0f_a_binary_tree.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#98 Added wheel library
  python/youtubedownloader.py
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#99 Added The Create and insert operation using php - HacktoberFest 2021
  php/Create_Insert.php
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#100 Create BubbleSort.java
  java/BubbleSort.java
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#101 added todo app in JS
  js/To-do app/fonts/Jost-Italic-VariableFont_wght.ttf
  js/To-do app/fonts/Jost-VariableFont_wght.ttf
  js/To-do app/fonts/PROPAGAN.ttf
  js/To-do app/fonts/akaPosse.ttf
  js/To-do app/fresh.js
  js/To-do app/index.html
  js/To-do app/style.css
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#102 add arraymap example.php
  php/array_map_example.php
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#103 Create InsertionSort.java
  java/InsertionSort.java
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#105 Create HeapSort.java
  java/HeapSort.java
Labels: hacktoberfest, hacktoberfest-accepted

#106 Create Cyclesort.java
  java/Cyclesort.java
Labels: hacktoberfest, hacktoberfest-accepted

#107 Create RadixSort.java
  java/RadixSort.java
Labels: hacktoberfest, hacktoberfest-accepted

#111 Add Rock,paper & Scissor in python
  python/Rock, Paper & Scissor.py
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#112 Create quiz.cpp
  cpp/quiz.cpp
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#113 Add if a number is majority element in a sorted array
  python/Check if a number is majority element in a sorted array.py
Labels: hacktoberfest, hacktoberfest-accepted

#115 analog clock
  js/analog_clock/5054.png
  js/analog_clock/analogclock.css
  js/analog_clock/analogclock.html
  js/analog_clock/analogclock.js
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#116 Created Temperature converter.java
  java/Temperature converter.java
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#117 Added Kth Ancestor of a node in Binary Tree
  cpp/kth Ancestor of a node in Binary tree.cpp
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#119 Added a program to print Fibonacci series using iteration
  cpp/Fibonacci_series.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#121 adding dijkstra's algo
  python/dijkstra.py
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#122 Create linearSearch.cpp
  cpp/linearSearch.cpp
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#125 A script to send whatsapp message with the use of pywhatkit module.
  python/whatsapp_automation_through_pywhatkit/README.md
  python/whatsapp_automation_through_pywhatkit/send_simple_message.py
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#127 Create bubblesort.py
  python/bubblesort.py
Labels: hacktoberfest, hacktoberfest-accepted

#128 Create Floyd's Triangle
  python/Floyd's Triangle
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, appreciation

#129 Added C++ implementation of LRU Cache
  cpp/LRU_Cache.cpp
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#165 My project - a time-synced lyrics finder using nodejs and python
  js/lyrics_finder/README.md
  js/lyrics_finder/requirements.txt
  js/lyrics_finder/search.js
  js/lyrics_finder/searcher.py
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#179 Improving linear Search in Linked List
  c/Improving linear Search in Linked List.c
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#130 Create selection_sort
  python/selection_sort
Labels: changes required, No DSA, no need

#131 added Sliding Window algo in java
  java/SlidingWindowMaximum.java
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#133 Added MD5Cryptor to encrypt decrypt password protected MD5
  java/MD5Cryptor
Labels: hacktoberfest, hacktoberfest-accepted

#134 Added Solution for Split Array Largest Sum Problem
  java/SplitArrayLargestSum.java
Labels: hacktoberfest, hacktoberfest-accepted

#136 Create GCD_aglorithm.java
  java/GCD_aglorithm.java
Labels: No DSA, no need

#138 Create qr code generator.py
  python/qr code generator.py
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#139 add double linked list in C++
  cpp/double linked list.cpp
Labels: No DSA, no need

#148 Create FloydTriangle.c
  c/FloydTriangle.c
Labels: No DSA, no need

#140 added merge sort
  python/Merge sort.py
Labels: No DSA, no need

#142 Input tag style changed
  js/weather-app/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#143 feat: js/quiz-app created
  js/quiz-app/index.html
  js/quiz-app/script.js
  js/quiz-app/style.css
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#144 Decrypting_XOR using python
  python/Decrypting_XOR.py
Labels: hacktoberfest, hacktoberfest-accepted

#192 CPP STL common programs added
  cpp/CPP STL/algorithm.cpp
  cpp/CPP STL/array.cpp
  cpp/CPP STL/deque.cpp
  cpp/CPP STL/list.cpp
  cpp/CPP STL/map.cpp
  cpp/CPP STL/priority_queue.cpp
  cpp/CPP STL/queue.cpp
  cpp/CPP STL/set.cpp
  cpp/CPP STL/stacks.cpp
  cpp/CPP STL/unordered_map.cpp
  cpp/CPP STL/unordered_set.cpp
  cpp/CPP STL/vector.cpp
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#176 add a tile matching game
  js/memory-game/LICENSE
  js/memory-game/README.md
  js/memory-game/game.html
  js/memory-game/script.js
  js/memory-game/style.css
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#183 converting number to rupee format
  c/convert_number_to_rupees.c
Labels: hacktoberfest, hacktoberfest-accepted

#185 Basic Inquiry Form Added
  php/Basic Inquiry Form/Images/bg.jpg
  php/Basic Inquiry Form/form.php
  php/Basic Inquiry Form/style.css
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#188 notepad.py
  python/notepad.py
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#189 Fitgit_Spinner.py
  python/Fitgit_spinner.py
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#191 Digital_clock.html
  html/Digital_Clock.html
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#197 Create airbrush.py
  python/Airbrush/airbrush.py
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#198 add calculator.php for hacktoberfest
  php/calculator.php
  python/bubblesort.py
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#200 Added A Console Game Called Guess The Number in Java - Hacktoberfest 2021
  java/Guess_The_Number.java
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#204 added search script and sending message to group script
  python/whatsapp_automation_through_pywhatkit/search.py
  python/whatsapp_automation_through_pywhatkit/send_togroup.py
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#201 Added Programs in Dart Language
  dart/1 Hello World.dart
  dart/10 Do while loop.dart
  dart/11 break and labels.dart
  dart/12 Continue.dart
  dart/13 Declaring Functions.dart
  dart/14 Function Expressions and Short Hand Syntax.dart
  dart/15 Required and Optional Parameters.dart
  dart/16 Optional Named Parameters.dart
  dart/17 Default Optional Parameters.dart
  dart/18 Exception Handling.dart
  dart/19 Custom Exception Handling Class.dart
  dart/2 comments.dart
  dart/20 Defining class and objects.dart
  dart/21 Constructors.dart
  dart/22 Getter and Setter.dart
  dart/23 Inheritance.dart
  dart/24 Method Overriding.dart
  dart/25 Constructor Inheritance.dart
  dart/26 Abstract methods and class.dart
  dart/27 Interface.dart
  dart/28 Static methods and variables.dart
  dart/29 Lambda Functions.dart
  dart/3 Data types and Variables.dart
  dart/30 Higher order functions.dart
  dart/31 Closures.dart
  dart/32 Fixed Length List.dart
  dart/33 Growable List.dart
  dart/34 Sets.dart
  dart/35 Maps.dart
  dart/36 Callable class.dart
  dart/4 Literals, Strings and String interpolation
  dart/5 Final and constant.dart
  dart/6 If and Else statements.dart
  dart/7 Conditional Expressions.dart
  dart/9 while loop.dart
Labels: hacktoberfest, hacktoberfest-accepted

#211 Added News Reader Script
  python/NewsReader/README.md
  python/NewsReader/news_reader.py
  python/NewsReader/screenshot/Output.png
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#215 Added Notification Reminder
  python/Notification_Reminder/README.md
  python/Notification_Reminder/notification.py
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#175 ADDED PING PONG SCORE KEEPER PROJECT
  js/Score-Keeper/README.md
  js/Score-Keeper/Score_keeper.Html
  js/Score-Keeper/img.jpg
  js/Score-Keeper/lisa-keffer-i0kB5B9J8Ds-unsplash.jpg
  js/Score-Keeper/scorekeeper.css
  js/Score-Keeper/scorekeeper.js
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#214 Create Phone book.java
  java/Phone book.java
Labels: hacktoberfest, hacktoberfest-accepted

#227 Added Android App :multipliaction tables using java
  android/tables/.gitignore
  android/tables/.idea/codeStyles/Project.xml
  android/tables/.idea/gradle.xml
  android/tables/.idea/misc.xml
  android/tables/.idea/runConfigurations.xml
  android/tables/app/.gitignore
  android/tables/app/build.gradle
  android/tables/app/proguard-rules.pro
  android/tables/app/src/androidTest/java/com/example/tables/ExampleInstrumentedTest.java
  android/tables/app/src/main/AndroidManifest.xml
  android/tables/app/src/main/java/com/example/tables/MainActivity.java
  android/tables/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  android/tables/app/src/main/res/drawable/ic_launcher_background.xml
  android/tables/app/src/main/res/drawable/tables.png
  android/tables/app/src/main/res/layout/activity_main.xml
  android/tables/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/tables/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/tables/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/tables/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/tables/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/tables/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/tables/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/tables/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/tables/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/tables/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/tables/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/tables/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/tables/app/src/main/res/values/colors.xml
  android/tables/app/src/main/res/values/strings.xml
  android/tables/app/src/main/res/values/styles.xml
  android/tables/app/src/test/java/com/example/tables/ExampleUnitTest.java
  android/tables/build.gradle
  android/tables/gradle.properties
  android/tables/gradle/wrapper/gradle-wrapper.jar
  android/tables/gradle/wrapper/gradle-wrapper.properties
  android/tables/gradlew
  android/tables/gradlew.bat
  android/tables/settings.gradle
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#230 Adding String Methods
  python/String Methods.ipynb
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#232 connecting 3 games (X-O)
  android/connecting3game-master/.gitignore
  android/connecting3game-master/app/.gitignore
  android/connecting3game-master/app/build.gradle
  android/connecting3game-master/app/google-services.json
  android/connecting3game-master/app/proguard-rules.pro
  android/connecting3game-master/app/src/androidTest/java/com/example/connecting3game/ExampleInstrumentedTest.java
  android/connecting3game-master/app/src/main/AndroidManifest.xml
  android/connecting3game-master/app/src/main/java/com/example/connecting3game/MainActivity.java
  android/connecting3game-master/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  android/connecting3game-master/app/src/main/res/drawable/board.png
  android/connecting3game-master/app/src/main/res/drawable/ic_launcher_background.xml
  android/connecting3game-master/app/src/main/res/drawable/red.png
  android/connecting3game-master/app/src/main/res/drawable/yellow.png
  android/connecting3game-master/app/src/main/res/layout/activity_main.xml
  android/connecting3game-master/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/connecting3game-master/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/connecting3game-master/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/connecting3game-master/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/connecting3game-master/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/connecting3game-master/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/connecting3game-master/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/connecting3game-master/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/connecting3game-master/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/connecting3game-master/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/connecting3game-master/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/connecting3game-master/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/connecting3game-master/app/src/main/res/values/colors.xml
  android/connecting3game-master/app/src/main/res/values/strings.xml
  android/connecting3game-master/app/src/main/res/values/styles.xml
  android/connecting3game-master/app/src/test/java/com/example/connecting3game/ExampleUnitTest.java
  android/connecting3game-master/build.gradle
  android/connecting3game-master/gradle.properties
  android/connecting3game-master/gradle/wrapper/gradle-wrapper.jar
  android/connecting3game-master/gradle/wrapper/gradle-wrapper.properties
  android/connecting3game-master/gradlew
  android/connecting3game-master/gradlew.bat
  android/connecting3game-master/settings.gradle
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#223 Added Flutter App called SPORTS_ARM
  flutter/Sports_Arm App/README.md
  flutter/Sports_Arm App/Screenshots/Screenshot_1633351116.png
  flutter/Sports_Arm App/Screenshots/Screenshot_1633351122.png
  flutter/Sports_Arm App/Screenshots/Screenshot_1633351128.png
  flutter/Sports_Arm App/Screenshots/Screenshot_1633351133.png
  flutter/Sports_Arm App/Screenshots/Screenshot_1633351136.png
  flutter/Sports_Arm App/Screenshots/Screenshot_1633351144.png
  flutter/Sports_Arm App/Screenshots/Screenshot_1633351158.png
  flutter/Sports_Arm App/android/app/build.gradle
  flutter/Sports_Arm App/android/app/src/debug/AndroidManifest.xml
  flutter/Sports_Arm App/android/app/src/main/AndroidManifest.xml
  flutter/Sports_Arm App/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
  flutter/Sports_Arm App/android/app/src/main/kotlin/com/example/sports_arm/MainActivity.kt
  flutter/Sports_Arm App/android/app/src/main/res/drawable-v21/launch_background.xml
  flutter/Sports_Arm App/android/app/src/main/res/drawable/launch_background.xml
  flutter/Sports_Arm App/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  flutter/Sports_Arm App/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  flutter/Sports_Arm App/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  flutter/Sports_Arm App/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  flutter/Sports_Arm App/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  flutter/Sports_Arm App/android/app/src/main/res/values-night/styles.xml
  flutter/Sports_Arm App/android/app/src/main/res/values/styles.xml
  flutter/Sports_Arm App/android/app/src/profile/AndroidManifest.xml
  flutter/Sports_Arm App/android/build.gradle
  flutter/Sports_Arm App/android/gradle.properties
  flutter/Sports_Arm App/android/gradle/wrapper/gradle-wrapper.jar
  flutter/Sports_Arm App/android/gradle/wrapper/gradle-wrapper.properties
  flutter/Sports_Arm App/android/gradlew
  flutter/Sports_Arm App/android/gradlew.bat
  flutter/Sports_Arm App/android/local.properties
  flutter/Sports_Arm App/android/settings.gradle
  flutter/Sports_Arm App/android/sports_arm_android.iml
  flutter/Sports_Arm App/lib/HomeScreen.dart
  flutter/Sports_Arm App/lib/acedemy_data.dart
  flutter/Sports_Arm App/lib/form.dart
  flutter/Sports_Arm App/lib/item_widget.dart
  flutter/Sports_Arm App/lib/main.dart
  flutter/Sports_Arm App/pubspec.lock
  flutter/Sports_Arm App/pubspec.yaml
  flutter/Sports_Arm App/readme.txt
  flutter/Sports_Arm App/sports_arm.iml
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#228 Created example of heading.html
  html/example of heading.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#235 Create Face_recognition.py
  python/Face_recognition.py
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#237 background generator project added
  js/backgroundGenerator/index.html
  js/backgroundGenerator/main.css
  js/backgroundGenerator/main.js
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#239 mini calculator with JS
  js/mini-calculator/bootstrap.min.css
  js/mini-calculator/index.html
  js/mini-calculator/main.css
  js/mini-calculator/main.js
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#242 Create sum of natural num using recursion.c
  sum of natural num using recursion.c
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#245 Create AI_voice_assistance.py
  AI_voice_assistance.py
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#249 magentic compass using sensor (android)
  android/magneticcomposs/.gitignore
  android/magneticcomposs/app/.gitignore
  android/magneticcomposs/app/build.gradle
  android/magneticcomposs/app/proguard-rules.pro
  android/magneticcomposs/app/src/androidTest/java/com/example/magneticcomposs/ExampleInstrumentedTest.java
  android/magneticcomposs/app/src/main/AndroidManifest.xml
  android/magneticcomposs/app/src/main/java/com/example/magneticcomposs/MainActivity.java
  android/magneticcomposs/app/src/main/res/drawable-v24/comp.jpg
  android/magneticcomposs/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  android/magneticcomposs/app/src/main/res/drawable-v24/nedel.png
  android/magneticcomposs/app/src/main/res/drawable/ic_launcher_background.xml
  android/magneticcomposs/app/src/main/res/layout/activity_main.xml
  android/magneticcomposs/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/magneticcomposs/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/magneticcomposs/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/magneticcomposs/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/magneticcomposs/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/magneticcomposs/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/magneticcomposs/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/magneticcomposs/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/magneticcomposs/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/magneticcomposs/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/magneticcomposs/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/magneticcomposs/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android/magneticcomposs/app/src/main/res/values/colors.xml
  android/magneticcomposs/app/src/main/res/values/strings.xml
  android/magneticcomposs/app/src/main/res/values/styles.xml
  android/magneticcomposs/app/src/test/java/com/example/magneticcomposs/ExampleUnitTest.java
  android/magneticcomposs/build.gradle
  android/magneticcomposs/gradle.properties
  android/magneticcomposs/gradle/wrapper/gradle-wrapper.jar
  android/magneticcomposs/gradle/wrapper/gradle-wrapper.properties
  android/magneticcomposs/gradlew
  android/magneticcomposs/gradlew.bat
  android/magneticcomposs/settings.gradle
Labels: hacktoberfest, hacktoberfest-accepted, appreciation

#250 Create index.html
  js/Digital Clock+Weather/index.html
Labels: hacktoberfest, hacktoberfest-accepted
